#!/bin/sh
# Requires `exiftool`
# Requires `zenity`

if ! command -v exiftool > /dev/null; then
    echo "\"exiftool\" is not installed."
    exit 1
fi

if ! command -v zenity &> /dev/null; then
    echo "\"zenity\" is not installed."
    exit 1
fi

if [ -z "${@}" ] || [ ! -f "${@}" ]; then
    echo "Specify a file."
    exit 1
fi

exiftool "${@}" | sed -r "s/:[ ]*/\n/" | zenity --list \
                                                --title="Exif Metadata of $@" \
                                                --text="" \
                                                --no-markup \
                                                --width=700 \
                                                --height=500 \
                                                --column="Tag" \
                                                --column="Data"
exit 0
