#!/bin/sh
# Requires `exiftool`
# Requires `zenity`

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps zenity exiftool

if [ -z "${@}" ] || [ ! -f "${@}" ]; then
    echo "Specify a file."
    exit 1
fi

exiftool "${@}" | sed -r "s/:[ ]*/\n/" | zenity --list \
                                                --title="Exif Metadata of $@" \
                                                --text="" \
                                                --no-markup \
                                                --width=700 \
                                                --height=500 \
                                                --column="Tag" \
                                                --column="Data"
exit 0
