#!/bin/sh

if [ -z "${@}" ]; then
	echo "Specify a file."
	exit 1
fi

exiftool "${@}" | sed -r "s/:[ ]*/\n/" | zenity --list \
												--title="Exif Metadata of $@" \
												--text="" \
												--no-markup \
												--width=700 \
												--height=500 \
												--column="Tag Name" \
												--column="Data"
