#!/bin/bash
# Requires `exiftool`
# Requires `kdialog`

if ! command -v exiftool &> /dev/null; then
    echo "\"exiftool\" is not installed."
    exit 1
fi

if ! command -v kdialog &> /dev/null; then
    echo "\"kdialog\" is not installed."
    exit 1
fi

if [ -z "${@}" ] || [ ! -f "${@}" ]; then
    echo "Specify a file."
    exit 1
fi

temp_file=$(mktemp)
exiftool "${@}" > "${temp_file}"
kdialog --title="Exif Metadata of ${@}" --textbox "${temp_file}" 800 500
rm "${temp_file}"
exit 0
