#!/usr/bin/env bash

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps kdialog exiftool

if [ -z "${@}" ] || [ ! -f "${@}" ]; then
    echo "No file specified." >&2
    if command -v notify-send > /dev/null; then
        notify-send -u critical -i dialog-error "Exifmetadata Error" "No file specified."
    fi
    exit 1
fi

temp_file=$(mktemp)
exiftool "${@}" > "${temp_file}"
kdialog --title="Exif Metadata of ${@}" --textbox "${temp_file}" 800 500
rm "${temp_file}"
exit 0
