#!/bin/sh

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps gamescope

exec env ENABLE_HDR_WSI=1 gamescope \
    --hdr-enabled \
    --hdr-debug-force-output \
    --force-grab-cursor \
    --fullscreen \
    --output-width 3440 \
    --output-height 1440 \
    --adaptive-sync \
    -- env ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 DISABLE_HDR_WSI=1 "$@"
    || notify-send -u critical -i error "Error Launching Application" "Failed to launch 'gamescope'."
