#!/bin/sh
# Requires `gamescope`

if ! command -v gamescope > /dev/null; then
    echo "\"gamescope\" is not installed."
    exit 1
fi

APPLICATION_NAME="$(basename "${0}")"

exec env ENABLE_HDR_WSI=1 gamescope \
    --hdr-enabled \
    --hdr-debug-force-output \
    --force-grab-cursor \
    --fullscreen \
    --output-width 3440 \
    --output-height 1440 \
    --adaptive-sync \
    -- env ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 DISABLE_HDR_WSI=1 "$@"
    || notify-send -u critical -i error "Error Launching Application" "Failed to launch ${APPLICATION_NAME}."
