#!/bin/bash
# Requires `man`
# Requires `fuzzel`
# Requires `xdg-terminal-exec`

LAUNCHER_CMD="fuzzel"
LAUNCHER_OPTS="-d"
TERMINAL="xdg-terminal-exec"
TERMINAL_OPTS=""

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo msg >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps man "${LAUNCHER_CMD}" "${TERMINAL}"

PAGES=$(man -k . 2>/dev/null | awk '{print $1}' | sort -u)
CHOICE=$(printf '%s\n' "${PAGES[@]}" | "${LAUNCHER_CMD}" ${LAUNCHER_OPTS} "$@")

if [ "${CHOICE}" ]; then
    PAGE=$(printf '%s\n' "${CHOICE}" | awk '{print $1}')
    exec "${TERMINAL}" ${TERMINAL_OPTS} man "${PAGE}"
else
    printf "Program Terminated\n"
fi
