#!/bin/bash
# Requires `man`

if ! command -v man &> /dev/null; then
    echo "\"man\" man is not installed"
    exit 1
fi

DMENU_CMD="fuzzel -d"

PAGES=$(man -k . 2>/dev/null | awk '{print $1}' | sort -u)
CHOICE=$(printf '%s\n' "${PAGES[@]}" | ${DMENU_CMD} "$@")

if [ "${CHOICE}" ]; then
    PAGE=$(printf '%s\n' "${CHOICE}" | awk '{print $1}')
    exec xdg-terminal-exec man "${PAGE}"
else
    printf "Program Terminated\n"
fi
