#!/usr/bin/env bash

LAUNCHER_CMD="fuzzel"
LAUNCHER_OPTS="-d"
EDITOR_CMD="code"
START_DIR="${1:-$HOME}"

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps "${LAUNCHER_CMD}" "${EDITOR_CMD}"

SELECTION=$(find "$START_DIR" -mindepth 1 -type d -print 2> /dev/null | "${LAUNCHER_CMD}" ${LAUNCHER_OPTS})

if [ -z "${SELECTION}" ]; then
    echo "No selection made."
    exit 0
fi

exec "${EDITOR_CMD}" "${SELECTION}"
