#!/bin/bash

DMENU_CMD="fuzzel -d"
EDITOR_CMD="code"
START_DIR="${1:-$HOME}"

if ! command -v $DMENU_CMD > /dev/null; then
    echo "Could not find dmenu-compatible launcher."
    exit 1
fi

if ! command -v $EDITOR_CMD &> /dev/null; then
    echo "Could not find Zed."
    exit 1
fi

SELECTION=$(find "$START_DIR" -mindepth 1 -type d -print 2> /dev/null | $DMENU_CMD)

if [ -z "$SELECTION" ]; then
    echo "No selection made."
    exit 0
fi

$EDITOR_CMD "$SELECTION"
