#!/bin/sh
# Requires `fuzzel`

DMENU_CMD="fuzzel -d"

if ! command -v $DMENU_CMD > /dev/null; then
    echo "Could not find dmenu-compatible launcher."
    exit 1
fi

case $(printf "󱅞 Lock\n󰶐 Turn Off Monitors\n󰷛 Lock and Turn Off Monitors\n󰩈 Log Out\n󰒲 Suspend\n Reboot\n󰑥 Soft Reboot\n Reboot into UEFI\n Reboot into Windows\n󰐥 Shutdown" | ${DMENU_CMD}) in
    "󱅞 Lock")
        loginctl lock-session
        ;;
    "󰶐 Turn Off Monitors")
        hyprctl dispatch dpms off
        ;;
    "󰷛 Lock and Turn Off Monitors")
        loginctl lock-session && hyprctl dispatch dpms off
        ;;
    "󰩈 Log Out")
        uwsm stop
        ;;
    "󰒲 Suspend")
        systemctl suspend
        ;;
    " Reboot")
        systemctl reboot
        ;;
    "󰑥 Soft Reboot")
        systemctl soft-reboot
        ;;
    " Reboot into UEFI")
        systemctl reboot --firmware-setup
        ;;
    " Reboot into Windows")
        systemctl reboot --boot-loader-entry=auto-windows
        ;;
    "󰐥 Shutdown")
        systemctl poweroff
        ;;
esac
