#!/bin/sh

DMENU_CMD="fuzzel -d"

case $(printf "󱅞 Lock\n󰶐 Turn Off Monitors\n󰷛 Lock and Turn Off Monitors\n󰩈 Log Out\n󰒲 Suspend\n Reboot\n Reboot into UEFI\n󰖳 Reboot into Windows\n󰑥 Soft Reboot\n󰐥 Shutdown" | ${DMENU_CMD}) in
    "󱅞 Lock")
        loginctl lock-session
        ;;
    "󰶐 Turn Off Monitors")
        hyprctl dispatch dpms off
        ;;
    "󰷛 Lock and Turn Off Monitors")
        loginctl lock-session && hyprctl dispatch dpms off
        ;;
    "󰩈 Log Out")
        uwsm stop
        ;;
    "󰒲 Suspend")
        systemctl suspend
        ;;
    " Reboot")
        systemctl reboot
        ;;
    " Reboot into UEFI")
        systemctl reboot --firmware-setup
        ;;
    "󰖳 Reboot into Windows")
        systemctl reboot --boot-loader-entry=auto-windows
        ;;
    "󰑥 Soft Reboot")
        systemctl soft-reboot
        ;;
    "󰐥 Shutdown")
        systemctl poweroff
        ;;
esac
