#!/bin/sh
# Requires "gpu-screen-recorder"

if ! command -v gpu-screen-recorder > /dev/null; then
    echo "\"gpu-screen-recorder\" is not installed"
    exit 1
fi

FILE="$(xdg-user-dir VIDEOS)/recordings/$(date +%Y-%m-%d_%H-%m-%s).mp4"

help_text() {
    if [ -n "${1}" ]; then
        error="${1}"
        printf "Error: %s\n\n" "${1}"
    fi
    printf "Description: Record screen using \"gpu-screen-recorder\".\n\nUsage:\n\tscreenrecording {start|stop|toggle}\n\nCommands:\n\tstart\t\tStart recording\n\tstop\t\tStop recording\n\ttoggle\t\tToggle recording on/off\n\t-h --help\tShow available commands\n"
}

get_pidfile() {
    find /tmp -maxdepth 1 -name "gpu-screen-recorder-*.pid" 2>/dev/null | head -n 1
}

is_running() {
    PIDFILE="$(get_pidfile)"
    [ -z "${PIDFILE}" ] && return 1

    PID="$(cat ${PIDFILE})"
    if ! ps -p ${PID} > /dev/null; then
        rm -f "${PIDFILE}"
        return 1
    fi

    return 0
}

start_recording() {
    if is_running; then
        notify-send -i media-record "Screen Recording" "A screen recording is already in progress."
        exit 1
    fi

    gpu-screen-recorder -w portal -f 60 -a "default_output|default_input" -ac opus -o "${FILE}" &
    PID=$!
    

    PIDFILE="$(mktemp -t gpu-screen-recorder-XXXX.pid)"
    printf "%s" "${PID}" > "${PIDFILE}"

    notify-send -i media-record "Screen Recording" "Screen recording started. It will be saved to ${FILE}."
}

stop_recording() {
    if ! is_running; then
        notify-send -u critical -i error "Screen Recording" "No screen recording is in progress."
        exit 1
    fi

    PIDFILE="$(get_pidfile)"
    PID="$(cat ${PIDFILE})"

    if kill -INT "${PID}" 2> /dev/null; then
        rm "${PIDFILE}"
        notify-send -i media-playback-stop "Screen Recording" "Screen recording stopped."
    else
        rm "${PIDFILE}"
        notify-send -u critical -i error "Screen Recording" "Failed to stop screen recording."
        exit 1
    fi
}

toggle_recording() {
    if is_running; then
        stop_recording
    else
        start_recording
    fi
}

if [ "${1}" = "start" ]; then
    start_recording
    exit 0
elif [ "${1}" = "stop" ]; then
    stop_recording
    exit 0
elif [ "${1}" = "toggle" ]; then
    toggle_recording
    exit 0
elif [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
    help_text
    exit 0
else
    help_text "Unknown command"
    exit 1
fi
