#!/bin/sh
# Requires "gpu-screen-recorder"

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

fatal() {
    msg="$1"
    echo "Runtime Error: $msg" >&2
    if command -v notify-send >/dev/null 2>&1; then
        notify-send -u critical -i dialog-error "Runtime Error" "$msg"
    fi

    exit 1
}

checkdeps gpu-screen-recorder xdg-user-dir notify-send

FILE="$(xdg-user-dir VIDEOS)/recordings/$(date +%Y-%m-%d_%H-%m-%s).mp4"

usage {
    printf "Description: Record screen using \"gpu-screen-recorder\".\n\nUsage:\n\tscreenrecording {start|stop|toggle}\n\nCommands:\n\tstart\t\tStart recording\n\tstop\t\tStop recording\n\ttoggle\t\tToggle recording on/off\n\t-h --help\tShow available commands\n"
}

get_pidfile() {
    find /tmp -maxdepth 1 -name "gpu-screen-recorder-*.pid" 2>/dev/null | head -n 1
}

is_running() {
    PIDFILE="$(get_pidfile)"
    [ -z "${PIDFILE}" ] && return 1

    PID="$(cat ${PIDFILE})"
    if ! ps -p ${PID} > /dev/null; then
        rm -f "${PIDFILE}"
        return 1
    fi

    return 0
}

start_recording() {
    if is_running; then
        notify-send -i media-record "Screen Recording" "A screen recording is already in progress."
        exit 1
    fi

    gpu-screen-recorder -w portal -f 60 -a "default_output|default_input" -ac opus -o "${FILE}" &
    PID=$!
    

    PIDFILE="$(mktemp -t gpu-screen-recorder-XXXX.pid)"
    printf "%s" "${PID}" > "${PIDFILE}"

    notify-send -i media-record "Screen Recording" "Screen recording started. It will be saved to ${FILE}."
}

stop_recording() {
    if ! is_running; then
        fatal "No screen recording is in progress."
    fi

    PIDFILE="$(get_pidfile)"
    PID="$(cat ${PIDFILE})"

    if kill -INT "${PID}" 2> /dev/null; then
        rm "${PIDFILE}"
        notify-send -i media-playback-stop "Screen Recording" "Screen recording stopped."
    else
        rm "${PIDFILE}"
        fatal "Failed to stop screen recording."
    fi
}

toggle_recording() {
    if is_running; then
        stop_recording
    else
        start_recording
    fi
}

case "${1:-}" in
    start)
        start_recording
        exit 0
        ;;
    stop)
        stop_recording
        exit 0
        ;;
    toggle)
        toggle_recording
        exit 0
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        
        usage
        fatal "Unknown Command: '${1-none}'."
        exit 1
        ;;
esac
