#!/bin/sh

VPN_STATUS=$(systemctl is-active wg-quick@pvpn.service)
if [ "${VPN_STATUS}" == "active" ]; then
	systemctl stop wg-quick@pvpn.service \
		&& notify-send -i network-vpn-disconnected "VPN Status" "Successfully disconnected from ProtonVPN" \
		|| notify-send -u critical -i error "VPN Status" "Failed to disconnect from ProtonVPN"
elif [ "${VPN_STATUS}" == "inactive" ]; then
	systemctl start wg-quick@pvpn.service \
		&& notify-send -i network-vpn "VPN Status" "Successfully connected to ProtonVPN" \
		|| notify-send -u critical -i error "VPN Status" "Failed to connect to ProtonVPN"
fi
