#!/bin/sh
# Requires `wg-quick`

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

fatal() {
    msg="$1"
    echo "Runtime Error: $msg" >&2
    if command -v notify-send >/dev/null 2>&1; then
        notify-send -u critical -i dialog-error "Runtime Error" "$msg"
    fi

    exit 1
}

checkdeps wg-quick notify-send

CONF_FILE="vpn"
VPN_STATUS="$(systemctl is-active wg-quick@${CONF_FILE}.service)"
if [ "${VPN_STATUS}" = "active" ]; then
    systemctl stop wg-quick@${CONF_FILE}.service \
        && notify-send -i network-vpn-disconnected-symbolic "VPN Status" "Successfully disconnected from VPN." \
        || notify-send -u critical -i error "VPN Status" "Failed to disconnect from VPN."
elif [ "${VPN_STATUS}" = "inactive" ]; then
    systemctl start wg-quick@${CONF_FILE}.service \
        && notify-send -i network-vpn-symbolic "VPN Status" "Successfully connected to VPN" \
        || notify-send -u critical -i error "VPN Status" "Failed to connect to VPN"
fi
