#!/bin/sh
# Requires `wg-quick`

if ! command -v wg-quick > /dev/null; then
    echo "\"wg-quick\" is not installed."
    exit 1
fi

CONF_FILE="vpn"
VPN_STATUS="$(systemctl is-active wg-quick@${CONF_FILE}.service)"
if [ "${VPN_STATUS}" = "active" ]; then
    systemctl stop wg-quick@${CONF_FILE}.service \
        && notify-send -i network-vpn-disconnected-symbolic "VPN Status" "Successfully disconnected from VPN." \
        || notify-send -u critical -i error "VPN Status" "Failed to disconnect from VPN."
elif [ "${VPN_STATUS}" = "inactive" ]; then
    systemctl start wg-quick@${CONF_FILE}.service \
        && notify-send -i network-vpn-symbolic "VPN Status" "Successfully connected to VPN" \
        || notify-send -u critical -i error "VPN Status" "Failed to connect to VPN"
fi
