#!/bin/sh

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps git

update_repos() {
    for dir in $(find "${1}" -mindepth 1 -maxdepth 1 -type d); do
        if [ -d "${dir}" ]; then
            printf "Checking directory: %s\n" "${dir}"
            if [ -d "${dir}/.git" ]; then
                printf "Pulling latest changes in %s...\n" "${dir}"
                cd "${dir}" || continue
                git pull
                cd - > /dev/null || exit
            else
                printf "%s is not a git repository, skipping.\n" "${dir}"
            fi
        fi
    done
    printf "Update Process Completed.\n"
}

if [ -d "${1}" ]; then
    update_repos "${1}"
    exit 0
else
    printf "Usage:\n\tupdate-repos </path/to/directory>\n"
    exit 1
fi
