#!/bin/bash
# Requires `wpctl`

STEP=1

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

fatal() {
    msg="$1"
    echo "Runtime Error: $msg" >&2
    if command -v notify-send >/dev/null 2>&1; then
        notify-send -u critical -i dialog-error "Runtime Error" "$msg"
    fi

    exit 1
}

checkdeps wpctl notify-send

getvol() {
    local volume=$(wpctl get-volume ${DEVICE} | awk '{print substr($2,0,4)}' | tr -d .)
    echo $((10#${volume}))
}

ismuted() {
    local mute_status=$(wpctl get-volume ${DEVICE} | awk '{print $3}')
    if [ "${mute_status}" == "[MUTED]" ]; then
        echo true
    else
        echo false
    fi
}

geticon() {
    if [ "$(getvol)" -eq "0" ] || [ "$(ismuted)" == "true" ]; then
        echo ${VOL_MUTE}
    elif [ "$(getvol)" -ge "0" ] && [ "$(getvol)" -le "30" ]; then
        echo ${VOL_LOW}
    elif [ "$(getvol)" -ge "30" ] && [ "$(getvol)" -le "60" ]; then
        echo ${VOL_MID}
    elif [ "$(getvol)" -ge "60" ] && [ "$(getvol)" -le "100" ]; then
        echo ${VOL_HIGH}
    fi
}

notify() {
    notify-send -t 1000 -e -h int:value:"$(getvol)" -h string:synchronous:volume -i "$(geticon)" "Volume" "Volume: $(getvol)%"
}

usage() {
    printf "Description: Control the volume of the default pipewire sink/source.\n\n"
    printf "Usage:\n\tvolume {output|input} <command>\n\n"
    printf "Commands:\n\t-g --get\tGet the volume of the default sink.\n\t-i --inc\tIncrement the volume of the default sink by %s%%.\n\t-d --dec\tDecrement the volume of the default sink by %s%%.\n\t-t --toggle\tToggle mute status of the default sink\n\t-s --set VOL%%\tSet the volume of the default sink to the specified value.\n\t-h --help\tShow available commands.\n" "${STEP}" "${STEP}"
}

stepvol() {
    wpctl set-volume -l 1 ${DEVICE} ${STEP}%${1}
    notify
}

togglemute() {
    if [ "$(ismuted)" == "true" ]; then
        wpctl set-mute ${DEVICE} 0
        notify
    else
        wpctl set-mute ${DEVICE} 1
        notify
    fi
}

setvol() {
    if [ -z "${1}" ]; then
        fatal "Enter the value you would like to change the volume to."
        exit 1
    else
        wpctl set-volume ${DEVICE} ${1}%
        notify
    fi
}

if [ "${1}" == "output" ]; then
    declare -g DEVICE="@DEFAULT_AUDIO_SINK@"
    declare -g VOL_HIGH="audio-volume-high"
    declare -g VOL_MID="audio-volume-medium"
    declare -g VOL_LOW="audio-volume-low"
    declare -g VOL_MUTE="audio-volume-muted"
elif [ "${1}" == "input" ]; then
    declare -g DEVICE="@DEFAULT_AUDIO_SOURCE@"
    declare -g VOL_HIGH="microphone-sensitivity-high"
    declare -g VOL_MID="microphone-sensitivity-medium"
    declare -g VOL_LOW="microphone-sensitivity-low"
    declare -g VOL_MUTE="microphone-sensitivity-muted"
else
    usage
    echo
    fatal 'The first argument must be either "output" or "input".'
    exit 1
fi

if [ "${2}" == "-g" ] || [ "${2}" == "--get" ]; then
    notify
    exit 0
elif [ "${2}" == "-i" ] || [ "${2}" == "--inc" ]; then
    stepvol "+"
    exit 0
elif [ "${2}" == "-d" ] || [ "${2}" == "--dec" ]; then
    stepvol "-"
    exit 0
elif [ "${2}" == "-t" ] || [ "${2}" == "--toggle" ]; then
    togglemute
    exit 0
elif [ "${2}" == "-s" ] || [ "${2}" == "--set" ]; then
    setvol "${3}"
    exit 0
elif [ "${2}" == "-h" ] || [ "${2}" == "--help" ] || [ -z "${2}" ]; then
    usage
    exit 0
else
    usage
    echo
    fatal "Unkown command."
    exit 1
fi
