#!/bin/sh

checkdeps() {
    for cmd in "${@}"; do
        if ! command -v "${cmd}" > /dev/null 2>&1; then
            msg="Could not find: '${cmd}'."
            echo ${msg} >&2
            if command -v notify-send > /dev/null 2>&1; then
                notify-send -u critical -i dialog-error "Missing Dependency" "${msg}"
            fi

            exit 1
        fi
    done
}

checkdeps curl

LOCATION=""
if [ -n "${WEATHER_LOCATION}" ]; then
    LOCATION="${WEATHER_LOCATION}"
else
    LOCATION="${1}"
fi

TEXT=$(curl -s "wttr.in/${LOCATION}?format=1")
TOOLTIP=$(curl -s "wttr.in/${LOCATION}?format=4")

printf '{"text":"%s", "tooltip":"%s"}\n' "${TEXT}" "${TOOLTIP}"
